### PR TITLE
Removed "mediaStatus" key for MediaStatus

### PR DESCRIPTION
**Pull request by neoassyrian**
@petrbela Please check if the change is correct and compiles. It was only a guess.

### CODE REVIEW

**Comment by petrbela** [comment]
Well, the fix is good but why did you delete the examples? I need them to test the app :)

**Comment by neoassyrian** [comment]
Oh, sorry, I had to do that in order to use it in my app from github directly (without using npm)
The example projects were failing to build. 

Will try to revert it back

**Comment by petrbela** [comment]
You're good, I'll just fix it on my local branch.

**Comment by neoassyrian** [comment]
Ok then
Just FYI, I still didn't get it to work even after the change I did. I just think it is probably my build or something that I'm doing wrong. I was expecting you to say what I did was wrong or something else needs to be done.

**Comment by petrbela** [comment]
That's really strange, it's working in the playground. Let me publish a new version and let's retest it.

**Pull request closed without merging**
