### PR TITLE
fix: prevent crash when GooglePlay services is missing or running on Android TV

### PR DESCRIPTION
**Pull request by henninghall**
fixes https://github.com/react-native-google-cast/react-native-google-cast/issues/287

### CODE REVIEW

**Comment by nth-zik** [comment]
Should merged

**Comment by Nikooos** [comment]
Would like to see this merged as we encounter a lot of crashreport with this issue. Does this also fix the problem with Huawei phones?

**Comment by alejandrorangel** [comment]
@petrbela when do you think this could be merged?

**Comment by alejandrorangel** [comment]
@petrbela any update on this ticket?

**Comment by chienduc91** [comment]
@petrbela I've been trying to solve this problem for days, but couldn't get it to work. Please help us

**Comment by alejandrorangel** [comment]
@petrbela are you still maintaining this repo?

**Comment by Nikooos** [comment]
I updated to this version in my app, but still see these crashes coming in. Are you experiencing the same? Else I'll have to check if it might be an issue on my side.

**Pull request merged**
